#+title: resumen

* Modelo logico relacional

- Paso intermedio entre el modelo conceptual y el interno
- Se basa en *las relaciones*. Nada mas

** Definiciones
*** Dominio
Conjunto de valores homogeneos
*** Producto cartesiano
Conjunto de todos los pares posibles entre los dominios
*** Relacion
*Subconjunto del producto cartesino*
*** Atributo
Miembros de la relacion.
*** Tupla
Una instancia de una relacion
*** Cardinalidad
Cantidad de tuplas de una relacion
*** Superclave
Subconjunto dentro de los atributos en un mismo tipo de tupla que *si o si* van a difererir.
*** Clave candidato
Un subconjunto de la superclave que es minimal.
*** Clave primaria
Algun elemento *arbitrario* de las claves candidatas que se usa como clave identificable "principal".

** Representacion
La representacion canonica de este modelo es el de la tabla. Cada atributo de la relacion es una columna y cada tupla una fila.

** Restricciones
*** Dominio
- Un valor debe pertenecer al dominio del atributo. No podes poner un string en una columna donde van ints.
- Se admiten ~NULL~ s
*** Unicidad
- No puede haber dos o mas tuplas iguales, cada tupla debe ser unica.
- Si no tenes ninguna superclave natural, podes generar un ID para poder distinguir las tuplas.
  - Pros:
    - Siempre funciona para diferenciar una tupla de otra.
  - Contra:
    - La BDD tiene que manejar la generacion e incremento del ID
    - El ID puede leaker informacion de order de ingreso a la BDD
*** Integridad de Entidad
La clave primaria *no* puede tomar valores nulos

*** Integridad de Referencial
Cuando se usa un valor de una tupla fuera de su origen (es decir, se una foreign key), ese valor *tiene que pertenecer al conjunto de la relacion*; no puede tomar *otro valor del dominio*.

Es decir, si vos usas un valor de tabla A como foreign key en tabla B, ese valor tiene que estar en la tabla A. No podes usar un valor que no este en la tabla aunque sea del mismo tipo

** Operaciones
Hay 4 operaciones. Algunas operaciones /pueden/ romper las restricciones del y en ese caso romper la integridad.

La siguiente tabla muestra que restricciones pueden romper cada operacion.

| Operacion    | Dominio | Unicidad | Int. Entidad | Int. Referencial |
|--------------+---------+----------+--------------+------------------|
| Consulta     | No      | No       | No           | No               |
| Eliminacion  | No      | No       | No           | Depende[fn:1]    |
| Insercion    | Si      | Si       | Si           | Depende[fn:2]    |
| Modificacion | Si      | Si       | Si           | Si               |

* Pasaje de Modelo
** Piedra de rosetta
*** N:1 participacion parcial
Esto sucede cuando el minimo que puede tomar el lado del 1 es 0.

Pasaje:
1. Creas una relacion por cada entidad
2. Creas una relacion por la inter relacion
3. La relacion de la inter-relacion va a tener como clave primaria la clave primaria del lado de los muchos
   1. ¿Por que? Porque entonces, los casos donde haya un 0 (es decir, no haya relacion) simplemente *no van a figurar en la relacion de la interrelacion*.
*** Entidad debil
1. Creas una relacion para la entidad debil.
2. Le anadis la *clave primaria de su entidad fuete como clave foranea*.
3. Ademas, la clave primaria va a ser *la tupla de su clave primaria con la clave foranea fuete*
   1. ¿Por que? Porque necesitas de *ambos* para poder distinguir una instancia particular de la entidad debil.
4. Si la inter relacion tiene atributos, anadis esos atributos como atributos de la entidad debil.
* Footnotes
[fn:2] Si la tupla que insertas usa de Foreign Key un valor que no existe, entonces si

[fn:1] Si la tupla que borras es la Foreign Key de otra tupla, entonces si se puede romper
